# .settings contains all settings related to the project and it's building of
# assets, themes and files.

# public contains settings related to the directory used for public assets which
# will be built and servable using the generated package.

app = "static"
package = "github.com/influx6/devapp/static"

[static]
indexDir = "./public" # sets where index.html will be located
jsFile = "static_app_bundle.js"
jsMapFile = "static_app_bundle.js.map"

[public]
path = "./public"
packageName = "static"

[theme]
PrimaryBrandColor = "#222222"
SecondaryBrandColor = "#444444"
